nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

api:
  image:
    repository: kubequeue-api
    tag: dev
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

worker:
  image:
    repository: kubequeue-worker
    tag: dev
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

web:
  image:
    repository: kubequeue-web
    tag: dev
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi
