nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  name: ''

rbac:
  create: true
  allowClusterWide: false

imagePullSecrets: []

watch:
  mode: selected
  namespaces: []
  excludedNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease

config:
  globalConcurrency: 10
  namespaceConcurrency: 5

runtime:
  environment: production

development:
  localAdminSeed: false

browser:
  publicURL: ''
  origin: ''

security:
  existingSecret: ''
  sessionDigestKey: session-digest-key
  credentialEncryptionKey: credential-encryption-key
  bffInternalKey: bff-internal-key
  serviceAccountDigestKey: service-account-digest-key

database:
  url: ''
  existingSecret: ''
  existingSecretKey: database-url

networkPolicy:
  enabled: true

api:
  image:
    repository: ghcr.io/atulfalle/kubequeue-api
    tag: ''
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

worker:
  image:
    repository: ghcr.io/atulfalle/kubequeue-worker
    tag: ''
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

web:
  image:
    repository: ghcr.io/atulfalle/kubequeue-web
    tag: ''
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi
