nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  name: ''

config:
  watchNamespaces: ''
  globalConcurrency: 10
  namespaceConcurrency: 5
  adminToken: ''
  adminTokenExistingSecret: ''
  adminTokenExistingSecretKey: admin-token

database:
  url: ''
  existingSecret: ''
  existingSecretKey: database-url

networkPolicy:
  enabled: false

api:
  image:
    repository: ghcr.io/atulfalle/kubequeue-api
    tag: ''
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

worker:
  image:
    repository: ghcr.io/atulfalle/kubequeue-worker
    tag: ''
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

web:
  image:
    repository: ghcr.io/atulfalle/kubequeue-web
    tag: ''
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi
