apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubequeue.fullname" . }}-config
  labels:
    {{- include "kubequeue.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.config.adminToken | quote }}
  {{- if not .Values.database.existingSecret }}
  {{ .Values.database.existingSecretKey }}: {{ required "database.url or database.existingSecret is required" .Values.database.url | quote }}
  {{- end }}
