{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubequeue.fullname" . }}-config
  labels:
    {{- include "kubequeue.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ required "database.url or database.existingSecret is required" .Values.database.url | quote }}
{{- end }}
