{{- if or (not .Values.config.adminTokenExistingSecret) (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubequeue.fullname" . }}-config
  labels:
    {{- include "kubequeue.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.config.adminTokenExistingSecret }}
  admin-token: {{ required "config.adminToken or config.adminTokenExistingSecret is required" .Values.config.adminToken | quote }}
  {{- end }}
  {{- if not .Values.database.existingSecret }}
  {{ .Values.database.existingSecretKey }}: {{ required "database.url or database.existingSecret is required" .Values.database.url | quote }}
  {{- end }}
{{- end }}
