apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubequeue.fullname" . }}-web
  labels:
    {{- include "kubequeue.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
