/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description Returns jobs matching the supplied inventory filters.
         */
        get: operations["listJobs"];
        put?: never;
        /**
         * Submit a job
         * @description Persists a standard Kubernetes Job template for queued execution.
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /**
         * Get a job
         * @description Returns the durable desired and Kubernetes-observed state for one job.
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /**
         * List job events
         * @description Returns immutable lifecycle events for one job.
         */
        get: operations["listJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
                action: "start" | "resume" | "pause" | "terminate" | "retry";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a lifecycle action
         * @description Changes durable intent or creates a linked retry attempt.
         */
        post: operations["commandJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a queue entry
         * @description Changes queue priority and position using optimistic concurrency.
         */
        patch: operations["updateQueuedJob"];
        trace?: never;
    };
    "/queue/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder queued jobs
         * @description Replaces queue positions when the supplied queue version is current.
         */
        put: operations["reorderQueue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream job changes
         * @description Streams job inventory snapshots as server-sent events.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JobState: "CREATED" | "QUEUED" | "RUNNING" | "PAUSED" | "COMPLETED" | "FAILED" | "CANCELLED";
        Job: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId?: string;
            name: string;
            namespace: string;
            team?: string;
            priority: number;
            position: number;
            desiredState: components["schemas"]["JobState"];
            observedState: components["schemas"]["JobState"];
            /** Format: date-time */
            scheduledFor?: string;
            kubernetesUid?: string;
            template: {
                [key: string]: unknown;
            };
            attempt: number;
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        JobList: {
            items: components["schemas"]["Job"][];
            count: number;
            queueVersion: number;
        };
        CreateJob: {
            name: string;
            namespace: string;
            team?: string;
            /** @default 0 */
            priority: number;
            /** Format: date-time */
            scheduledFor?: string;
            template: {
                [key: string]: unknown;
            };
        };
        JobEvent: {
            id: number;
            /** Format: uuid */
            jobId: string;
            type: string;
            message: string;
            data?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                status: number;
            };
        };
    };
    responses: {
        /** @description Request failed */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        JobId: string;
        Status: components["schemas"]["JobState"];
        Namespace: string;
        Team: string;
        Priority: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listJobs: {
        parameters: {
            query?: {
                status?: components["parameters"]["Status"];
                namespace?: components["parameters"]["Namespace"];
                team?: components["parameters"]["Team"];
                priority?: components["parameters"]["Priority"];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJob"];
            };
        };
        responses: {
            /** @description Job queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listJobEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable lifecycle history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobEvent"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    commandJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
                action: "start" | "resume" | "pause" | "terminate" | "retry";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated job or new retry attempt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateQueuedJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    priority: number;
                    position: number;
                    version: number;
                    /** Format: date-time */
                    scheduledFor?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated queue entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    reorderQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    jobIds: string[];
                    version: number;
                };
            };
        };
        responses: {
            /** @description New queue version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: number;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent job snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Error"];
        };
    };
}
